name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run: |
          npm install --global pnpm
          pnpm install

      - name: Build Next.js app
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/deploy-to-github-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination: gh-pages
          push: true
          folder: out
